import React, { FormEvent, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import './live.css'

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000'
const DEMO_MODE = import.meta.env.VITE_DEMO_MODE === 'true'
const USER_ID = (()=>{const saved=localStorage.getItem('best-gift-user');if(saved)return saved;const created=`web-${crypto.randomUUID()}`;localStorage.setItem('best-gift-user',created);return created})()
type Event = {id:string;phase:string;agent:string;message:string}
type Result = {thread_id:string;summary:string;intent:{budget:number;currency:string;recipient?:string;occasion?:string;age?:number;exclusions?:string[]};recommendations:Array<{product:{id:string;name:string;description:string;image:string;merchant:string;rating:number;url:string};total_cost:number;score:number;reasons:string[];caveat?:string}>;events:Event[];evaluation?:{overall:number;passed:boolean;relevance:number;budget_fit:number;diversity:number;explainability:number;notes:string[]}}

const demoAsset=(filename:string)=>`${import.meta.env.BASE_URL}products/${filename}`
type DemoItem = {product:Result['recommendations'][number]['product'];total_cost:number;keywords:string[];group:string;audiences:string[];occasions:string[];minAge?:number}
const demoCatalog:DemoItem[]=[
  {product:{id:'travel-coffee',name:'Travel Coffee Ritual Kit',description:'A compact pour-over set, hand grinder, and origin coffees for mornings anywhere.',image:demoAsset('travel-coffee-kit.jpg'),merchant:'Etsy search',rating:4.9,url:'https://www.etsy.com/search?q=travel%20coffee%20pour%20over%20kit'},total_cost:68,keywords:['coffee','travel','food','outdoors'],group:'coffee',audiences:['partner','sibling','friend','parent','coworker'],occasions:['birthday','holiday','graduation']},
  {product:{id:'coffee-sampler',name:'Artisan Coffee Tasting Sampler',description:'A gift-ready selection of small-batch coffees with tasting notes.',image:demoAsset('travel-coffee-kit.jpg'),merchant:'Etsy search',rating:4.7,url:'https://www.etsy.com/search?q=artisan%20coffee%20tasting%20sampler%20gift'},total_cost:28,keywords:['coffee','food','experience'],group:'coffee',audiences:['partner','sibling','friend','parent','coworker'],occasions:['birthday','holiday','thank-you']},
  {product:{id:'travel-journal',name:'Personalized Travel Journal',description:'A personalized journal with pockets for tickets, notes, and keepsakes.',image:demoAsset('personalized-travel-journal.jpg'),merchant:'Etsy search',rating:4.8,url:'https://www.etsy.com/search?q=personalized%20travel%20journal'},total_cost:54,keywords:['travel','writing','art','personalized'],group:'journal',audiences:['partner','sibling','friend','parent'],occasions:['birthday','anniversary','graduation']},
  {product:{id:'recipe-journal',name:'Personalized Recipe Journal',description:'A custom recipe notebook for preserving favorite dishes and family stories.',image:demoAsset('personalized-travel-journal.jpg'),merchant:'Etsy search',rating:4.7,url:'https://www.etsy.com/search?q=personalized%20recipe%20journal'},total_cost:30,keywords:['writing','cooking','personalized','family'],group:'journal',audiences:['parent','partner','sibling','friend'],occasions:['birthday','holiday','mothers-day']},
  {product:{id:'ceramic-tasting',name:'Ceramic Tasting Set',description:'Handmade tasting cups designed to bring a favorite café ritual home.',image:demoAsset('ceramic-tasting-set.jpg'),merchant:'Etsy search',rating:4.8,url:'https://www.etsy.com/search?q=handmade%20ceramic%20coffee%20tasting%20cup%20set'},total_cost:72,keywords:['coffee','tea','art','home'],group:'ceramic',audiences:['partner','friend','parent','coworker'],occasions:['birthday','wedding','housewarming']},
  {product:{id:'ceramic-cup',name:'Handmade Tasting Cup',description:'A one-of-a-kind glazed cup for a quiet coffee or tea ritual.',image:demoAsset('ceramic-tasting-set.jpg'),merchant:'Etsy search',rating:4.8,url:'https://www.etsy.com/search?q=handmade%20ceramic%20tasting%20cup'},total_cost:34,keywords:['coffee','tea','art','home'],group:'ceramic',audiences:['partner','friend','parent','coworker'],occasions:['birthday','thank-you','housewarming']},
  {product:{id:'city-explorer',name:'Weekend City Explorer',description:'An illustrated guide and prompt deck for planning memorable micro-adventures.',image:demoAsset('weekend-city-explorer.jpg'),merchant:'Etsy search',rating:4.7,url:'https://www.etsy.com/search?q=city%20adventure%20travel%20gift'},total_cost:39,keywords:['travel','adventure','outdoors','experience'],group:'adventure',audiences:['partner','sibling','friend','child'],occasions:['birthday','graduation','anniversary'],minAge:8},
  {product:{id:'travel-cards',name:'Travel Adventure Prompt Cards',description:'A pocket deck of playful prompts for memorable day trips and vacations.',image:demoAsset('weekend-city-explorer.jpg'),merchant:'Etsy search',rating:4.6,url:'https://www.etsy.com/search?q=travel%20adventure%20prompt%20cards'},total_cost:24,keywords:['travel','adventure','outdoors','experience'],group:'adventure',audiences:['partner','sibling','friend','child'],occasions:['birthday','graduation','holiday'],minAge:8},
  {product:{id:'indoor-garden',name:'Smart Indoor Herb Garden',description:'A countertop grow light and self-watering planter for fresh herbs year-round.',image:demoAsset('smart-indoor-herb-garden.jpg'),merchant:'Etsy search',rating:4.7,url:'https://www.etsy.com/search?q=smart%20indoor%20herb%20garden'},total_cost:79,keywords:['gardening','cooking','technology','home'],group:'garden',audiences:['parent','partner','friend'],occasions:['birthday','mothers-day','housewarming']},
  {product:{id:'herb-starter',name:'Kitchen Herb Seed Starter',description:'A compact windowsill kit with culinary herb seeds and reusable planters.',image:demoAsset('smart-indoor-herb-garden.jpg'),merchant:'Etsy search',rating:4.6,url:'https://www.etsy.com/search?q=kitchen%20herb%20seed%20starter%20gift'},total_cost:26,keywords:['gardening','cooking','home'],group:'garden',audiences:['parent','partner','friend','coworker'],occasions:['birthday','mothers-day','housewarming']},
  {product:{id:'night-sky',name:'Custom Night Sky Print',description:'A framed star map celebrating a meaningful date and place.',image:demoAsset('custom-night-sky-print.jpg'),merchant:'Etsy search',rating:4.9,url:'https://www.etsy.com/search?q=custom%20night%20sky%20star%20map'},total_cost:45,keywords:['astronomy','romance','art','personalized'],group:'sky',audiences:['partner','parent','sibling','friend'],occasions:['anniversary','wedding','birthday']},
  {product:{id:'sky-print-small',name:'Personalized Mini Star Map',description:'A compact custom night-sky print marking a special date.',image:demoAsset('custom-night-sky-print.jpg'),merchant:'Etsy search',rating:4.8,url:'https://www.etsy.com/search?q=personalized%20mini%20star%20map'},total_cost:32,keywords:['astronomy','romance','art','personalized'],group:'sky',audiences:['partner','parent','sibling','friend'],occasions:['anniversary','wedding','birthday']},
  {product:{id:'tea-ceremony',name:'Japanese Tea Ceremony Set',description:'A hand-glazed matcha bowl, bamboo whisk, scoop, caddy, and linen cloth.',image:demoAsset('japanese-tea-ceremony-set.jpg'),merchant:'Etsy search',rating:4.8,url:'https://www.etsy.com/search?q=japanese%20tea%20ceremony%20set'},total_cost:64,keywords:['tea','mindfulness','culture','cooking'],group:'tea',audiences:['parent','partner','friend','coworker'],occasions:['birthday','holiday','mothers-day']},
  {product:{id:'matcha-starter',name:'Matcha Starter Set',description:'An approachable whisk, scoop, and matcha sampler for a calming daily ritual.',image:demoAsset('japanese-tea-ceremony-set.jpg'),merchant:'Etsy search',rating:4.7,url:'https://www.etsy.com/search?q=matcha%20starter%20gift%20set'},total_cost:29,keywords:['tea','mindfulness','culture','cooking'],group:'tea',audiences:['parent','partner','friend','coworker'],occasions:['birthday','holiday','thank-you']},
  {product:{id:'robot-kit',name:'Build-Your-Own Robot Kit',description:'A friendly programmable robot with modular sensors and family challenges.',image:demoAsset('robot-kit.jpg'),merchant:'Etsy search',rating:4.7,url:'https://www.etsy.com/search?q=build%20your%20own%20robot%20kit'},total_cost:74,keywords:['technology','science','family','education'],group:'robot',audiences:['child','sibling','friend'],occasions:['birthday','holiday','graduation'],minAge:10},
  {product:{id:'robot-junior',name:'Junior Robot Discovery Kit',description:'A screen-free beginner robot project with illustrated science challenges.',image:demoAsset('robot-kit.jpg'),merchant:'Etsy search',rating:4.8,url:'https://www.etsy.com/search?q=junior%20robot%20science%20kit'},total_cost:29,keywords:['technology','science','family','education'],group:'robot',audiences:['child'],occasions:['birthday','holiday','graduation'],minAge:7},
]
const interests=[
  {label:'coffee',terms:['coffee','espresso','咖啡']},{label:'travel',terms:['travel','traveler','trip','journey','旅行','旅游']},
  {label:'gardening',terms:['garden','gardening','plants','herb','园艺','花园','植物']},{label:'cooking',terms:['cook','cooking','kitchen','烹饪','厨房','做饭','下厨']},
  {label:'technology',terms:['technology','tech','gadget','robot','科技','技术','机器人']},{label:'science',terms:['science','stem','科学']},
  {label:'tea',terms:['tea','matcha','茶','抹茶']},{label:'mindfulness',terms:['mindful','meditation','wellness','冥想','正念']},
  {label:'astronomy',terms:['astronomy','stars','night sky','space','天文','星空']},{label:'romance',terms:['romantic','anniversary','romance','浪漫','纪念日']},
  {label:'writing',terms:['writing','journal','notebook','写作','手账','日记']},{label:'art',terms:['art','design','ceramic','艺术','设计','陶瓷']},
  {label:'outdoors',terms:['outdoors','hiking','camping','adventure','户外','徒步','露营']},{label:'family',terms:['family','kids','child','家庭','孩子']},
  {label:'personalized',terms:['personalized','custom','unique','定制','个性化']},{label:'culture',terms:['culture','japanese','文化','日式']},
]
function hash(text:string){return [...text].reduce((value,char)=>(value*31+char.charCodeAt(0))>>>0,7)}
function parseBudget(text:string){const marked=text.match(/(?:under|below|budget|max(?:imum)?|以内|预算)\D{0,10}(\d{1,4})/i);const symbol=text.match(/[$£€]\s*(\d{1,4})/);return Number(marked?.[1]||symbol?.[1]||80)}
const recipientProfiles=[
  {label:'child',terms:['child','kid','son','daughter','boy','girl','孩子','儿子','女儿','儿童'],preferences:['science','technology','education','adventure','family']},
  {label:'parent',terms:['mother','mom','mum','father','dad','parent','妈妈','母亲','爸爸','父亲','父母'],preferences:['gardening','cooking','tea','home','mindfulness','personalized']},
  {label:'partner',terms:['wife','husband','partner','girlfriend','boyfriend','spouse','妻子','丈夫','伴侣','爱人','女朋友','男朋友'],preferences:['romance','personalized','travel','art','experience']},
  {label:'sibling',terms:['sister','brother','sibling','姐姐','妹妹','哥哥','弟弟','兄弟姐妹'],preferences:['travel','art','personalized','coffee','technology']},
  {label:'coworker',terms:['coworker','colleague','boss','manager','同事','同僚','老板','经理'],preferences:['coffee','tea','writing','home']},
  {label:'friend',terms:['friend','bestie','朋友','好友'],preferences:['experience','travel','art','personalized']},
]
const occasionProfiles=[
  {label:'anniversary',terms:['anniversary','纪念日']},{label:'birthday',terms:['birthday','生日']},{label:'graduation',terms:['graduation','graduate','毕业']},
  {label:'wedding',terms:['wedding','结婚','婚礼']},{label:'holiday',terms:['christmas','holiday','xmas','圣诞','节日']},{label:'mothers-day',terms:["mother's day",'mothers day','母亲节']},
  {label:'housewarming',terms:['housewarming','new home','乔迁','新居']},{label:'thank-you',terms:['thank you','appreciation','感谢','答谢']},
]
function detectExclusions(text:string){
  const normalized=text.toLowerCase();const excluded=new Set<string>()
  for(const interest of interests)for(const term of interest.terms){const escaped=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');if(new RegExp(`(?:no|not|avoid|without|doesn['’]?t like|不要|避免|不喜欢|不想要)[^,.，。]{0,18}${escaped}`,'i').test(normalized))excluded.add(interest.label)}
  return [...excluded]
}
function detectAge(text:string){const match=text.match(/(?:age(?:d)?\s*|)(\d{1,2})[-\s]?(?:year[-\s]?old|years? old|岁)/i);return match?Number(match[1]):undefined}
function buildDemoResult(text:string,country:string):Result{
  const normalized=text.toLowerCase();const exclusions=detectExclusions(text);const detected=interests.filter(item=>!exclusions.includes(item.label)&&item.terms.some(term=>normalized.includes(term))).map(item=>item.label)
  const recipient=recipientProfiles.find(profile=>profile.terms.some(term=>normalized.includes(term)))||{label:'recipient',terms:[],preferences:[]};const occasion=occasionProfiles.find(profile=>profile.terms.some(term=>normalized.includes(term)))?.label||'gift';const budget=parseBudget(text);const age=detectAge(text)
  const eligible=demoCatalog.filter(item=>!item.keywords.some(keyword=>exclusions.includes(keyword))&&(!age||!item.minAge||age>=item.minAge)&&(recipient.label!=='child'||item.audiences.includes('child')))
  const withinBudget=eligible.filter(item=>item.total_cost<=budget);const pool=withinBudget.length?withinBudget:eligible
  const scored=pool.map(item=>{const explicit=item.keywords.filter(keyword=>detected.includes(keyword));const profile=item.keywords.filter(keyword=>recipient.preferences.includes(keyword));const audience=item.audiences.includes(recipient.label)?1:0;const occasionMatch=item.occasions.includes(occasion)?1:0;const budgetValue=item.total_cost<=budget?Math.min(1,item.total_cost/Math.max(budget,1)):0;const score=Math.min(99,Math.round(38+explicit.length*18+profile.length*6+audience*9+occasionMatch*8+budgetValue*6+item.product.rating));return {...item,explicit,profile,score}}).sort((a,b)=>b.score-a.score||b.product.rating-a.product.rating||a.total_cost-b.total_cost)
  const ranked:typeof scored=[];const groups=new Set<string>();for(const item of scored){if(groups.has(item.group))continue;groups.add(item.group);ranked.push(item);if(ranked.length===4)break}
  const recommendations=ranked.map(item=>({product:item.product,total_cost:item.total_cost,score:item.score,reasons:[item.explicit.length?`Matches stated interests: ${item.explicit.join(', ')}`:item.profile.length?`Fits common ${recipient.label} preferences: ${item.profile.join(', ')}`:`Suitable for a ${recipient.label} ${occasion}`,item.total_cost<=budget?`Within the USD ${budget} budget`:`Closest available option to the USD ${budget} budget`],caveat:item.total_cost>budget?`No eligible catalog item fits USD ${budget}; this option is USD ${item.total_cost-budget} over budget.`:undefined}))
  const safePreferences=recipient.preferences.filter(preference=>!exclusions.includes(preference));const focus=detected.length?detected.slice(0,3).join(', '):safePreferences.slice(0,3).join(', ')||'versatile interests';const relevance=Math.min(100,64+detected.length*9+(recipient.label!=='recipient'?8:0)+(occasion!=='gift'?6:0));const budgetFit=recommendations.length?Math.round(100*recommendations.filter(item=>item.total_cost<=budget).length/recommendations.length):0
  const context=[recipient.label!=='recipient'?recipient.label:null,age?`age ${age}`:null,occasion!=='gift'?occasion:null].filter(Boolean).join(', ')||'general recipient';const exclusionText=exclusions.length?` Excluded: ${exclusions.join(', ')}.`:''
  const events:Event[]=[{id:'1',phase:'think',agent:'orchestrator',message:`Parsed ${context} with a hard USD ${budget} budget for ${country}.`},{id:'2',phase:'act',agent:'recipient',message:`Semantic profile: ${focus}.${exclusionText}`},{id:'3',phase:'observe',agent:'catalog',message:`Filtered ${demoCatalog.length} candidates by recipient, age, exclusions, and budget; ${pool.length} remained.`},{id:'4',phase:'reflect',agent:'value',message:'Reranked by explicit interests, recipient fit, occasion fit, value, and category diversity.'}]
  return {thread_id:`github-pages-${hash(text).toString(16)}`,summary:`Ideas for ${context}, matched to ${focus} within USD ${budget}.`,intent:{budget,currency:'USD',recipient:recipient.label,occasion,age,exclusions},recommendations,events,evaluation:{overall:Math.round((relevance+budgetFit+88+92)/4),passed:recommendations.length>0,relevance,budget_fit:budgetFit,diversity:88,explainability:92,notes:exclusions.length?[`Excluded ${exclusions.join(', ')} products.`]:[]}}
}

function App(){
  const [message,setMessage]=useState('A thoughtful birthday gift for my sister who loves coffee and travel, under $80')
  const [country,setCountry]=useState('US'); const [result,setResult]=useState<Result|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [threadId,setThreadId]=useState('')
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');if(DEMO_MODE){setResult(buildDemoResult(message,country));setLoading(false);return}const id=result?.thread_id||crypto.randomUUID().replaceAll('-','');setThreadId(id);try{const r=await fetch(`${API}/api/search`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message,country,thread_id:id,user_id:USER_ID})});if(!r.ok)throw new Error(r.status===409?'Search cancelled':'Search failed');setResult(await r.json())}catch(e){setError(e instanceof Error?e.message:'Search failed')}finally{setLoading(false)}}
  async function cancel(){if(threadId){await fetch(`${API}/api/threads/${threadId}/cancel`,{method:'POST'});setError('Cancellation requested')}}
  async function vote(id:string,value:number){if(DEMO_MODE){return}if(result)await fetch(`${API}/api/threads/${result.thread_id}/feedback`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({product_id:id,value,user_id:USER_ID})})}
  return <main>
    <header><a className="brand" href="#">Best Gift Search<span>✦</span></a><span className="tag">{DEMO_MODE?'GitHub Pages interactive demo':'Thoughtful gifts, globally compared'}</span></header>
    <section className="hero"><p className="eyebrow">MULTI-AGENT GIFT CONCIERGE</p><h1>Find the gift that feels<br/><em>exactly right.</em></h1><p>Tell us who they are. Our specialists search, compare, and explain the best matches—without the endless tabs.</p>
      <form onSubmit={submit}><textarea value={message} onChange={e=>setMessage(e.target.value)} aria-label="Describe the gift"/><div className="formbar"><select value={country} onChange={e=>setCountry(e.target.value)} aria-label="Delivery country"><option>US</option><option>CA</option><option>GB</option></select>{loading&&!DEMO_MODE&&<button type="button" className="cancel" onClick={cancel}>Cancel</button>}<button disabled={loading}>{loading?'Finding gifts…':'Find gifts →'}</button></div></form>{DEMO_MODE&&<p className="demo-banner">Semantic browser demo: recipient, age, occasion, interests, exclusions, and budget rank sixteen representative products. Clone the repository to run the live FastAPI agents.</p>}{error&&<p className="error">{error}</p>}
    </section>
    {result&&<><section className="process"><div><span>01</span><b>Understand</b><small>Recipient profile</small></div><div><span>02</span><b>Explore</b><small>Parallel search</small></div><div><span>03</span><b>Compare</b><small>Delivered value</small></div><div><span>04</span><b>Reflect</b><small>Explain matches</small></div></section>
      <section className="results"><div className="sectionhead"><div><p className="eyebrow">CURATED FOR YOU</p><h2>{result.summary}</h2></div><p>{result.recommendations.length} standout ideas · under {result.intent.currency} {result.intent.budget}</p></div><div className="grid">{result.recommendations.map((r,i)=><article key={r.product.id}><div className="photo"><img src={r.product.image} alt={`${r.product.name} recommendation`} loading="lazy"/><span>#{i+1} · {r.score}% match</span></div><div className="cardbody"><small>{r.product.merchant} · ★ {r.product.rating}</small><h3>{r.product.name}</h3><p>{r.product.description}</p><ul>{r.reasons.slice(0,2).map(x=><li key={x}>{x}</li>)}</ul>{r.caveat&&<p className="caveat">{r.caveat}</p>}<div className="price"><b>{result.intent.currency} {r.total_cost.toFixed(0)}</b><a href={r.product.url}>{r.product.url.includes('/search?')?'Shop similar →':'View gift →'}</a></div>{!DEMO_MODE&&<div className="vote">Helpful? <button aria-label={`Mark ${r.product.name} helpful`} onClick={()=>vote(r.product.id,1)}>Yes</button><button aria-label={`Mark ${r.product.name} unhelpful`} onClick={()=>vote(r.product.id,-1)}>No</button></div>}</div></article>)}</div></section>
      {result.evaluation&&<section className="rubric"><div><p className="eyebrow">AUTOMATED QUALITY RUBRIC</p><h2>{result.evaluation.overall}/100 <small>{result.evaluation.passed?'Passed':'Needs review'}</small></h2></div>{[['Relevance',result.evaluation.relevance],['Budget fit',result.evaluation.budget_fit],['Diversity',result.evaluation.diversity],['Explainability',result.evaluation.explainability]].map(([label,value])=><div className="meter" key={String(label)}><span>{label}</span><b>{value}</b><progress max="100" value={Number(value)}/></div>)}</section>}
      <details><summary>How the agents reached this answer</summary>{result.events.map(e=><p key={e.id}><b>{e.phase}</b> · {e.agent} — {e.message}</p>)}</details></>}
    <footer>Best Gift Search · Explainable recommendations · No sponsored ranking</footer>
  </main>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
