import React, { FormEvent, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import './live.css'

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000'
type Event = {id:string;phase:string;agent:string;message:string}
type Result = {thread_id:string;summary:string;intent:{budget:number;currency:string};recommendations:Array<{product:{id:string;name:string;description:string;image:string;merchant:string;rating:number;url:string};total_cost:number;score:number;reasons:string[];caveat?:string}>;events:Event[];evaluation?:{overall:number;passed:boolean;relevance:number;budget_fit:number;diversity:number;explainability:number;notes:string[]}}

function App(){
  const [message,setMessage]=useState('A thoughtful birthday gift for my sister who loves coffee and travel, under $80')
  const [country,setCountry]=useState('US'); const [result,setResult]=useState<Result|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [liveEvents,setLiveEvents]=useState<Event[]>([]); const [threadId,setThreadId]=useState('')
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');setLiveEvents([]);const id=result?.thread_id||crypto.randomUUID().replaceAll('-','');setThreadId(id);const socket=new WebSocket(`${API.replace(/^http/,'ws')}/ws/${id}`);socket.onmessage=e=>setLiveEvents(old=>[...old,JSON.parse(e.data)]);try{await new Promise<void>((resolve,reject)=>{socket.onopen=()=>resolve();socket.onerror=()=>reject(new Error('Live connection failed'))});const r=await fetch(`${API}/api/search`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message,country,thread_id:id})});if(!r.ok)throw new Error(r.status===409?'Search cancelled':'Search failed');setResult(await r.json())}catch(e){setError(e instanceof Error?e.message:'Search failed')}finally{socket.close();setLoading(false)}}
  async function cancel(){if(threadId){await fetch(`${API}/api/threads/${threadId}/cancel`,{method:'POST'});setError('Cancellation requested')}}
  async function vote(id:string,value:number){if(result)await fetch(`${API}/api/threads/${result.thread_id}/feedback`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({product_id:id,value})})}
  return <main>
    <header><a className="brand" href="#">Best Gift Search<span>✦</span></a><span className="tag">Thoughtful gifts, globally compared</span></header>
    <section className="hero"><p className="eyebrow">MULTI-AGENT GIFT CONCIERGE</p><h1>Find the gift that feels<br/><em>exactly right.</em></h1><p>Tell us who they are. Our specialists search, compare, and explain the best matches—without the endless tabs.</p>
      <form onSubmit={submit}><textarea value={message} onChange={e=>setMessage(e.target.value)} aria-label="Describe the gift"/><div className="formbar"><select value={country} onChange={e=>setCountry(e.target.value)} aria-label="Delivery country"><option>US</option><option>CA</option><option>GB</option></select>{loading&&<button type="button" className="cancel" onClick={cancel}>Cancel</button>}<button disabled={loading}>{loading?'Agents working…':'Find gifts →'}</button></div></form>{error&&<p className="error">{error}</p>}{loading&&<div className="live" aria-live="polite">{liveEvents.map(e=><span key={e.id}><b>{e.agent}</b> {e.message}</span>)}</div>}
    </section>
    {result&&<><section className="process"><div><span>01</span><b>Understand</b><small>Recipient profile</small></div><div><span>02</span><b>Explore</b><small>Parallel search</small></div><div><span>03</span><b>Compare</b><small>Delivered value</small></div><div><span>04</span><b>Reflect</b><small>Explain matches</small></div></section>
      <section className="results"><div className="sectionhead"><div><p className="eyebrow">CURATED FOR YOU</p><h2>{result.summary}</h2></div><p>{result.recommendations.length} standout ideas · under {result.intent.currency} {result.intent.budget}</p></div><div className="grid">{result.recommendations.map((r,i)=><article key={r.product.id}><div className="photo"><img src={r.product.image} alt=""/><span>#{i+1} · {r.score}% match</span></div><div className="cardbody"><small>{r.product.merchant} · ★ {r.product.rating}</small><h3>{r.product.name}</h3><p>{r.product.description}</p><ul>{r.reasons.slice(0,2).map(x=><li key={x}>{x}</li>)}</ul>{r.caveat&&<p className="caveat">{r.caveat}</p>}<div className="price"><b>{result.intent.currency} {r.total_cost.toFixed(0)}</b><a href={r.product.url}>View gift ↗</a></div><div className="vote">Helpful? <button onClick={()=>vote(r.product.id,1)}>Yes</button><button onClick={()=>vote(r.product.id,-1)}>No</button></div></div></article>)}</div></section>
      {result.evaluation&&<section className="rubric"><div><p className="eyebrow">AUTOMATED QUALITY RUBRIC</p><h2>{result.evaluation.overall}/100 <small>{result.evaluation.passed?'Passed':'Needs review'}</small></h2></div>{[['Relevance',result.evaluation.relevance],['Budget fit',result.evaluation.budget_fit],['Diversity',result.evaluation.diversity],['Explainability',result.evaluation.explainability]].map(([label,value])=><div className="meter" key={String(label)}><span>{label}</span><b>{value}</b><progress max="100" value={Number(value)}/></div>)}</section>}
      <details><summary>How the agents reached this answer</summary>{result.events.map(e=><p key={e.id}><b>{e.phase}</b> · {e.agent} — {e.message}</p>)}</details></>}
    <footer>Best Gift Search · Explainable recommendations · No sponsored ranking</footer>
  </main>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
