import React, { FormEvent, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import './live.css'

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000'
const DEMO_MODE = import.meta.env.VITE_DEMO_MODE === 'true'
const USER_ID = (()=>{const saved=localStorage.getItem('best-gift-user');if(saved)return saved;const created=`web-${crypto.randomUUID()}`;localStorage.setItem('best-gift-user',created);return created})()
type Event = {id:string;phase:string;agent:string;message:string}
type Result = {thread_id:string;summary:string;intent:{budget:number;currency:string};recommendations:Array<{product:{id:string;name:string;description:string;image:string;merchant:string;rating:number;url:string};total_cost:number;score:number;reasons:string[];caveat?:string}>;events:Event[];evaluation?:{overall:number;passed:boolean;relevance:number;budget_fit:number;diversity:number;explainability:number;notes:string[]}}

const demoImage=(a:string,b:string,symbol:string)=>`data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 440"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient></defs><rect width="640" height="440" fill="url(#g)"/><circle cx="530" cy="360" r="190" fill="white" opacity=".12"/><circle cx="70" cy="40" r="100" fill="none" stroke="white" opacity=".2"/><text x="320" y="255" text-anchor="middle" font-size="140" fill="white">${symbol}</text></svg>`)}`
const demoResult:Result={thread_id:'github-pages-demo',summary:'Four thoughtful ways to bring her coffee ritual on every journey.',intent:{budget:80,currency:'USD'},recommendations:[
  {product:{id:'demo-1',name:'Travel Coffee Ritual Kit',description:'A compact pour-over set, hand grinder, and origin coffees for mornings anywhere.',image:demoImage('#9fb9aa','#375b50','☕'),merchant:'Marketplace search',rating:4.9,url:'https://www.etsy.com/search?q=travel%20coffee%20pour%20over%20kit'},total_cost:68,score:94,reasons:['Matches coffee + travel','Complete landed cost']},
  {product:{id:'demo-2',name:'Personalized Travel Journal',description:'A personalized journal with pockets for tickets, notes, and keepsakes.',image:demoImage('#ddb996','#9c664b','✦'),merchant:'Marketplace search',rating:4.8,url:'https://www.etsy.com/search?q=personalized%20travel%20journal'},total_cost:54,score:89,reasons:['Thoughtful personalization','Easy international delivery']},
  {product:{id:'demo-3',name:'Ceramic Tasting Set',description:'Handmade tasting cups designed to bring a favorite café ritual home.',image:demoImage('#b0c7cc','#597984','◒'),merchant:'Marketplace search',rating:4.8,url:'https://www.etsy.com/search?q=handmade%20ceramic%20coffee%20tasting%20cup%20set'},total_cost:72,score:86,reasons:['Strong recipient fit','Independent maker']},
  {product:{id:'demo-4',name:'Weekend City Explorer',description:'An illustrated guide or prompt deck for planning memorable micro-adventures.',image:demoImage('#d7c9a6','#827b58','⌁'),merchant:'Marketplace search',rating:4.7,url:'https://www.etsy.com/search?q=city%20adventure%20travel%20gift'},total_cost:39,score:82,reasons:['Experience-led gift','Comfortably in budget']},
],events:[{id:'1',phase:'think',agent:'orchestrator',message:'Parsed recipient, occasion, interests, country, and budget.'},{id:'2',phase:'act',agent:'recipient',message:'Built a coffee-loving traveler profile.'},{id:'3',phase:'observe',agent:'catalog',message:'Retrieved and reranked candidates across categories.'},{id:'4',phase:'reflect',agent:'value',message:'Compared delivered totals and recommendation diversity.'}],evaluation:{overall:78.2,passed:true,relevance:84,budget_fit:100,diversity:62,explainability:67,notes:[]}}

function App(){
  const [message,setMessage]=useState('A thoughtful birthday gift for my sister who loves coffee and travel, under $80')
  const [country,setCountry]=useState('US'); const [result,setResult]=useState<Result|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [liveEvents,setLiveEvents]=useState<Event[]>([]); const [threadId,setThreadId]=useState('')
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');setLiveEvents([]);if(DEMO_MODE){for(const event of demoResult.events){await new Promise(resolve=>setTimeout(resolve,180));setLiveEvents(old=>[...old,event])}setResult(demoResult);setLoading(false);return}const id=result?.thread_id||crypto.randomUUID().replaceAll('-','');setThreadId(id);const socket=new WebSocket(`${API.replace(/^http/,'ws')}/ws/${id}`);socket.onmessage=e=>setLiveEvents(old=>[...old,JSON.parse(e.data)]);try{await new Promise<void>((resolve,reject)=>{socket.onopen=()=>resolve();socket.onerror=()=>reject(new Error('Live connection failed'))});const r=await fetch(`${API}/api/search`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message,country,thread_id:id,user_id:USER_ID})});if(!r.ok)throw new Error(r.status===409?'Search cancelled':'Search failed');setResult(await r.json())}catch(e){setError(e instanceof Error?e.message:'Search failed')}finally{socket.close();setLoading(false)}}
  async function cancel(){if(threadId){await fetch(`${API}/api/threads/${threadId}/cancel`,{method:'POST'});setError('Cancellation requested')}}
  async function vote(id:string,value:number){if(DEMO_MODE){return}if(result)await fetch(`${API}/api/threads/${result.thread_id}/feedback`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({product_id:id,value,user_id:USER_ID})})}
  return <main>
    <header><a className="brand" href="#">Best Gift Search<span>✦</span></a><span className="tag">{DEMO_MODE?'GitHub Pages interactive demo':'Thoughtful gifts, globally compared'}</span></header>
    <section className="hero"><p className="eyebrow">MULTI-AGENT GIFT CONCIERGE</p><h1>Find the gift that feels<br/><em>exactly right.</em></h1><p>Tell us who they are. Our specialists search, compare, and explain the best matches—without the endless tabs.</p>
      <form onSubmit={submit}><textarea value={message} onChange={e=>setMessage(e.target.value)} aria-label="Describe the gift"/><div className="formbar"><select value={country} onChange={e=>setCountry(e.target.value)} aria-label="Delivery country"><option>US</option><option>CA</option><option>GB</option></select>{loading&&!DEMO_MODE&&<button type="button" className="cancel" onClick={cancel}>Cancel</button>}<button disabled={loading}>{loading?'Agents working…':'Find gifts →'}</button></div></form>{DEMO_MODE&&<p className="demo-banner">Public demo uses representative results. Clone the repository to run the live FastAPI agents.</p>}{error&&<p className="error">{error}</p>}{loading&&<div className="live" aria-live="polite">{liveEvents.map(e=><span key={e.id}><b>{e.agent}</b> {e.message}</span>)}</div>}
    </section>
    {result&&<><section className="process"><div><span>01</span><b>Understand</b><small>Recipient profile</small></div><div><span>02</span><b>Explore</b><small>Parallel search</small></div><div><span>03</span><b>Compare</b><small>Delivered value</small></div><div><span>04</span><b>Reflect</b><small>Explain matches</small></div></section>
      <section className="results"><div className="sectionhead"><div><p className="eyebrow">CURATED FOR YOU</p><h2>{result.summary}</h2></div><p>{result.recommendations.length} standout ideas · under {result.intent.currency} {result.intent.budget}</p></div><div className="grid">{result.recommendations.map((r,i)=><article key={r.product.id}><div className="photo"><img src={r.product.image} alt={`${r.product.name} recommendation`}/><span>#{i+1} · {r.score}% match</span></div><div className="cardbody"><small>{r.product.merchant} · ★ {r.product.rating}</small><h3>{r.product.name}</h3><p>{r.product.description}</p><ul>{r.reasons.slice(0,2).map(x=><li key={x}>{x}</li>)}</ul>{r.caveat&&<p className="caveat">{r.caveat}</p>}<div className="price"><b>{result.intent.currency} {r.total_cost.toFixed(0)}</b><a href={r.product.url} target="_blank" rel="noopener noreferrer">{r.product.url.includes('/search?')?'Shop similar ↗':'View gift ↗'}</a></div>{!DEMO_MODE&&<div className="vote">Helpful? <button aria-label={`Mark ${r.product.name} helpful`} onClick={()=>vote(r.product.id,1)}>Yes</button><button aria-label={`Mark ${r.product.name} unhelpful`} onClick={()=>vote(r.product.id,-1)}>No</button></div>}</div></article>)}</div></section>
      {result.evaluation&&<section className="rubric"><div><p className="eyebrow">AUTOMATED QUALITY RUBRIC</p><h2>{result.evaluation.overall}/100 <small>{result.evaluation.passed?'Passed':'Needs review'}</small></h2></div>{[['Relevance',result.evaluation.relevance],['Budget fit',result.evaluation.budget_fit],['Diversity',result.evaluation.diversity],['Explainability',result.evaluation.explainability]].map(([label,value])=><div className="meter" key={String(label)}><span>{label}</span><b>{value}</b><progress max="100" value={Number(value)}/></div>)}</section>}
      <details><summary>How the agents reached this answer</summary>{result.events.map(e=><p key={e.id}><b>{e.phase}</b> · {e.agent} — {e.message}</p>)}</details></>}
    <footer>Best Gift Search · Explainable recommendations · No sponsored ranking</footer>
  </main>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
